# Copyright 1998 Richie Bielak and others
# Licensed under Eiffel Forum Freeware License, version 1;
# (see forum.txt)

ROOT=$(EGTK)/examples/drawing
EIFFEL_ROOT_CLASS= drawing
EIFFEL_CREATION_ROUTINE= make

all: 
	$(EGTK)/bin/egtkbuild drawing

clean:
	-rm -f *.o *.h *.c *~
	-rm -f $(EIFFEL_ROOT_CLASS)
	-rm -f *.make

