# Makefile for top-level examples directory

.DEFAULT all clean:
	$(MAKE) -C drawing $@
	$(MAKE) -C events $@
	$(MAKE) -C fixed_text $@
	$(MAKE) -C hello $@
	$(MAKE) -C gnome_canvas $@
	$(MAKE) -C image-scribble-simple $@
	$(MAKE) -C menu $@
	$(MAKE) -C packing $@
	$(MAKE) -C pixmap $@
	$(MAKE) -C range_widgets $@
	$(MAKE) -C testgtk $@
	$(MAKE) -C tictactoe $@
	$(MAKE) -C tree $@
